version: '3'
services:
  db:
    image: mongo:4.2
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongo-data:/data/db
  fake-zebra-printer:
    image: zakodium/fake-zebra-printer:1.0.0
    ports:
      - 127.0.0.1:4001:80
volumes:
  mongo-data:
