name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Lint with ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: npm install and eslint
        run: |
          npm ci
          npm run eslint
        env:
          CI: true
