name: Docker Image CI

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login docker.pkg.github.com -u ${{ secrets.GITHUB_DOCKER_USER }} -p ${{ secrets.GITHUB_DOCKER_TOKEN }}
      - name: Build and push the Docker image
        run: |
          docker build . -t docker.pkg.github.com/zakodium/label-print-server/server:${GITHUB_REF##*/}
          docker push docker.pkg.github.com/zakodium/label-print-server/server:${GITHUB_REF##*/}
